name: First CI Pipeline

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: build
        run: go build -o app ./cmd/app/main.go

      - name: informing
        if: github.event_name == "push" && github.ref == "refs/heads/master"
        run: echo "Deploy completed"
      

on:
pull_request:
    branches: [ develop, master ]